spring:
  application:
    name: Weather-based travel helper
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

resilience4j:
  retry:
    instances:
      placesRetry:
        max-attempts: 5
        wait-duration: 2s
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException

tomtom:
  api:
    key: ${TOMTOM.API.KEY}
frontend:
  url: ${FRONTEND_URL}